import 'package:flutter_test/flutter_test.dart';

class KannadaTransliterator {
  Map<String, String> kannadaCharList = {};
  Map<String, String> kagunita = {
    'ಅ': 'a',
    'ಆ': 'aa',
    'ಇ': 'i',
    'ಈ': 'ii',
    'ಉ': 'u',
    'ಊ': 'uu',
    'ಋ': 'r',
    'ೠ': 'rr',
    'ಎ': 'e',
    'ಏ': 'ee',
    'ಐ': 'ai',
    'ಒ': 'o',
    'ಓ': 'oo',
    'ಔ': 'au',
    'ಅಂ': 'ah',
    'ಅಃ': 'k',
    'ಕ': 'ka',
    'ಕಾ': 'kaa',
    'ಕಿ': 'ki',
    'ಕೀ': 'kii',
    'ಕು': 'ku',
    'ಕೂ': 'kuu',
    'ಕೃ': 'kr',
    'ಕೆ': 'ke',
    'ಕೇ': 'kee',
    'ಕೈ': 'kai',
    'ಕೊ': 'ko',
    'ಕೋ': 'koo',
    'ಕೌ': 'kau',
    'ಕಂ': 'kam',
    'ಕಃ': 'kah',
    'ಖ': 'kha',
    'ಖಾ': 'khaa',
    'ಖಿ': 'khi',
    'ಖೀ': 'khii',
    'ಖು': 'khu',
    'ಖೂ': 'khuu',
    'ಖೃ': 'khr',
    'ಖೆ': 'khe',
    'ಖೇ': 'khee',
    'ಖೈ': 'khai',
    'ಖೊ': 'kho',
    'ಖೋ': 'khoo',
    'ಖೌ': 'khau',
    'ಖಂ': 'kham',
    'ಖಃ': 'khah',
    'ಗ': 'ga',
    'ಗಾ': 'gaa',
    'ಗಿ': 'gi',
    'ಗೀ': 'gii',
    'ಗು': 'gu',
    'ಗೂ': 'guu',
    'ಗೃ': 'gr',
    'ಗೆ': 'ge',
    'ಗೇ': 'gee',
    'ಗೈ': 'gai',
    'ಗೊ': 'go',
    'ಗೋ': 'goo',
    'ಗೌ': 'gau',
    'ಗಂ': 'gam',
    'ಗಃ': 'gah',
    'ಘ': 'gha',
    'ಘಾ': 'ghaa',
    'ಘಿ': 'ghi',
    'ಘೀ': 'ghii',
    'ಘು': 'ghu',
    'ಘೂ': 'ghuu',
    'ಘೃ': 'ghr',
    'ಘೆ': 'ghe',
    'ಘೇ': 'ghee',
    'ಘೈ': 'ghai',
    'ಘೊ': 'gho',
    'ಘೋ': 'ghoo',
    'ಘೌ': 'ghau',
    'ಘಂ': 'gham',
    'ಘಃ': 'ghah',
    'ಙ': 'nga',
    'ಙಾ': 'ngaa',
    'ಙಿ': 'ngi',
    'ಙೀ': 'ngii',
    'ಙು': 'ngu',
    'ಙೂ': 'nguu',
    'ಙೃ': 'ngr',
    'ಙೆ': 'nge',
    'ಙೇ': 'ngee',
    'ಙೈ': 'ngai',
    'ಙೊ': 'ngo',
    'ಙೋ': 'ngoo',
    'ಙೌ': 'ngau',
    'ಙಂ': 'ngam',
    'ಙಃ': 'ngah',
    'ಚ': 'cha',
    'ಚಾ': 'chaa',
    'ಚಿ': 'chi',
    'ಚೀ': 'chii',
    'ಚು': 'chu',
    'ಚೂ': 'chuu',
    'ಚೃ': 'chr',
    'ಚೆ': 'che',
    'ಚೇ': 'chee',
    'ಚೈ': 'chai',
    'ಚೊ': 'cho',
    'ಚೋ': 'choo',
    'ಚೌ': 'chau',
    'ಚಂ': 'cham',
    'ಚಃ': 'chah',
    'ಛ': 'chha',
    'ಛಾ': 'chhaa',
    'ಛಿ': 'chhi',
    'ಛೀ': 'chhii',
    'ಛು': 'chhu',
    'ಛೂ': 'chhuu',
    'ಛೃ': 'chhr',
    'ಛೆ': 'chhe',
    'ಛೇ': 'chhee',
    'ಛೈ': 'chhai',
    'ಛೊ': 'chho',
    'ಛೋ': 'chhoo',
    'ಛೌ': 'chhau',
    'ಛಂ': 'chham',
    'ಛಃ': 'chhah',
    'ಜ': 'ja',
    'ಜಾ': 'jaa',
    'ಜಿ': 'ji',
    'ಜೀ': 'jii',
    'ಜು': 'ju',
    'ಜೂ': 'juu',
    'ಜೃ': 'jr',
    'ಜೆ': 'je',
    'ಜೇ': 'jee',
    'ಜೈ': 'jai',
    'ಜೊ': 'jo',
    'ಜೋ': 'joo',
    'ಜೌ': 'jau',
    'ಜಂ': 'jam',
    'ಜಃ': 'jah',
    'ಝ': 'jha',
    'ಝಾ': 'jhaa',
    'ಝಿ': 'jhi',
    'ಝೀ': 'jhii',
    'ಝು': 'jhu',
    'ಝೂ': 'jhuu',
    'ಝೃ': 'jhr',
    'ಝೆ': 'jhe',
    'ಝೇ': 'jhee',
    'ಝೈ': 'jhai',
    'ಝೊ': 'jho',
    'ಝೋ': 'jhoo',
    'ಝೌ': 'jhau',
    'ಝಂ': 'jham',
    'ಝಃ': 'jhah',
    'ಞ': 'nya',
    'ಞಾ': 'nyaa',
    'ಞಿ': 'nyi',
    'ಞೀ': 'nyii',
    'ಞು': 'nyu',
    'ಞೂ': 'nyuu',
    'ಞೃ': 'nyr',
    'ಞೆ': 'nye',
    'ಞೇ': 'nyee',
    'ಞೈ': 'nyai',
    'ಞೊ': 'nyo',
    'ಞೋ': 'nyoo',
    'ಞೌ': 'nyau',
    'ಞಂ': 'nyam',
    'ಞಃ': 'nyah',
    'ಟ': 'tta',
    'ಟಾ': 'ttaa',
    'ಟಿ': 'tti',
    'ಟೀ': 'ttii',
    'ಟು': 'ttu',
    'ಟೂ': 'ttuu',
    'ಟೃ': 'ttr',
    'ಟೆ': 'tte',
    'ಟೇ': 'ttee',
    'ಟೈ': 'ttai',
    'ಟೊ': 'tto',
    'ಟೋ': 'ttoo',
    'ಟೌ': 'ttau',
    'ಟಂ': 'ttam',
    'ಟಃ': 'ttah',
    'ಠ': 'ttha',
    'ಠಾ': 'tthaa',
    'ಠಿ': 'tthi',
    'ಠೀ': 'tthii',
    'ಠು': 'tthu',
    'ಠೂ': 'tthuu',
    'ಠೃ': 'tthr',
    'ಠೆ': 'tthe',
    'ಠೇ': 'tthee',
    'ಠೈ': 'tthai',
    'ಠೊ': 'ttho',
    'ಠೋ': 'tthoo',
    'ಠೌ': 'tthau',
    'ಠಂ': 'ttham',
    'ಠಃ': 'tthah',
    'ಡ': 'dda',
    'ಡಾ': 'ddaa',
    'ಡಿ': 'ddi',
    'ಡೀ': 'ddii',
    'ಡು': 'ddu',
    'ಡೂ': 'dduu',
    'ಡೃ': 'ddr',
    'ಡೆ': 'dde',
    'ಡೇ': 'ddee',
    'ಡೈ': 'ddai',
    'ಡೊ': 'ddo',
    'ಡೋ': 'ddoo',
    'ಡೌ': 'ddau',
    'ಡಂ': 'ddam',
    'ಡಃ': 'ddah',
    'ಢ': 'ddha',
    'ಢಾ': 'ddhaa',
    'ಢಿ': 'ddhi',
    'ಢೀ': 'ddhii',
    'ಢು': 'ddhu',
    'ಢೂ': 'ddhuu',
    'ಢೃ': 'ddhr',
    'ಢೆ': 'ddhe',
    'ಢೇ': 'ddhee',
    'ಢೈ': 'ddhai',
    'ಢೊ': 'ddho',
    'ಢೋ': 'ddhoo',
    'ಢೌ': 'ddhau',
    'ಢಂ': 'ddham',
    'ಢಃ': 'ddhah',
    'ಣ': 'nna',
    'ಣಾ': 'nnaa',
    'ಣಿ': 'nni',
    'ಣೀ': 'nnii',
    'ಣು': 'nnu',
    'ಣೂ': 'nnuu',
    'ಣೃ': 'nnr',
    'ಣೆ': 'nne',
    'ಣೇ': 'nnee',
    'ಣೈ': 'nnai',
    'ಣೊ': 'nno',
    'ಣೋ': 'nnoo',
    'ಣೌ': 'nnau',
    'ಣಂ': 'nnam',
    'ಣಃ': 'nnah',
    'ತ': 'ta',
    'ತಾ': 'taa',
    'ತಿ': 'ti',
    'ತೀ': 'tii',
    'ತು': 'tu',
    'ತೂ': 'tuu',
    'ತೃ': 'tr',
    'ತೆ': 'te',
    'ತೇ': 'tee',
    'ತೈ': 'tai',
    'ತೊ': 'to',
    'ತೋ': 'too',
    'ತೌ': 'tau',
    'ತಂ': 'tam',
    'ತಃ': 'tah',
    'ಥ': 'tha',
    'ಥಾ': 'thaa',
    'ಥಿ': 'thi',
    'ಥೀ': 'thii',
    'ಥು': 'thu',
    'ಥೂ': 'thuu',
    'ಥೃ': 'thr',
    'ಥೆ': 'the',
    'ಥೇ': 'thee',
    'ಥೈ': 'thai',
    'ಥೊ': 'tho',
    'ಥೋ': 'thoo',
    'ಥೌ': 'thau',
    'ಥಂ': 'tham',
    'ಥಃ': 'thah',
    'ದ': 'da',
    'ದಾ': 'daa',
    'ದಿ': 'di',
    'ದೀ': 'dii',
    'ದು': 'du',
    'ದೂ': 'duu',
    'ದೃ': 'dr',
    'ದೆ': 'de',
    'ದೇ': 'dee',
    'ದೈ': 'dai',
    'ದೊ': 'do',
    'ದೋ': 'doo',
    'ದೌ': 'dau',
    'ದಂ': 'dam',
    'ದಃ': 'dah',
    'ಧ': 'dha',
    'ಧಾ': 'dhaa',
    'ಧಿ': 'dhi',
    'ಧೀ': 'dhii',
    'ಧು': 'dhu',
    'ಧೂ': 'dhuu',
    'ಧೃ': 'dhr',
    'ಧೆ': 'dhe',
    'ಧೇ': 'dhee',
    'ಧೈ': 'dhai',
    'ಧೊ': 'dho',
    'ಧೋ': 'dhoo',
    'ಧೌ': 'dhau',
    'ಧಂ': 'dham',
    'ಧಃ': 'dhah',
    'ನ': 'na',
    'ನಾ': 'naa',
    'ನಿ': 'ni',
    'ನೀ': 'nii',
    'ನು': 'nu',
    'ನೂ': 'nuu',
    'ನೃ': 'nr',
    'ನೆ': 'ne',
    'ನೇ': 'nee',
    'ನೈ': 'nai',
    'ನೊ': 'no',
    'ನೋ': 'noo',
    'ನೌ': 'nau',
    'ನಂ': 'nam',
    'ನಃ': 'nah',
    'ಪ': 'pa',
    'ಪಾ': 'paa',
    'ಪಿ': 'pi',
    'ಪೀ': 'pii',
    'ಪು': 'pu',
    'ಪೂ': 'puu',
    'ಪೃ': 'pr',
    'ಪೆ': 'pe',
    'ಪೇ': 'pee',
    'ಪೈ': 'pai',
    'ಪೊ': 'po',
    'ಪೋ': 'poo',
    'ಪೌ': 'pau',
    'ಪಂ': 'pam',
    'ಪಃ': 'pah',
    'ಫ': 'pha',
    'ಫಾ': 'phaa',
    'ಫಿ': 'phi',
    'ಫೀ': 'phii',
    'ಫು': 'phu',
    'ಫೂ': 'phuu',
    'ಫೃ': 'phr',
    'ಫೆ': 'phe',
    'ಫೇ': 'phee',
    'ಫೈ': 'phai',
    'ಫೊ': 'pho',
    'ಫೋ': 'phoo',
    'ಫೌ': 'phau',
    'ಫಂ': 'pham',
    'ಫಃ': 'phah',
    'ಬ': 'ba',
    'ಬಾ': 'baa',
    'ಬಿ': 'bi',
    'ಬೀ': 'bii',
    'ಬು': 'bu',
    'ಬೂ': 'buu',
    'ಬೃ': 'br',
    'ಬೆ': 'be',
    'ಬೇ': 'bee',
    'ಬೈ': 'bai',
    'ಬೊ': 'bo',
    'ಬೋ': 'boo',
    'ಬೌ': 'bau',
    'ಬಂ': 'bam',
    'ಬಃ': 'bah',
    'ಭ': 'bha',
    'ಭಾ': 'bhaa',
    'ಭಿ': 'bhi',
    'ಭೀ': 'bhii',
    'ಭು': 'bhu',
    'ಭೂ': 'bhuu',
    'ಭೃ': 'bhr',
    'ಭೆ': 'bhe',
    'ಭೇ': 'bhee',
    'ಭೈ': 'bhai',
    'ಭೊ': 'bho',
    'ಭೋ': 'bhoo',
    'ಭೌ': 'bhau',
    'ಭಂ': 'bham',
    'ಭಃ': 'bhah',
    'ಮ': 'ma',
    'ಮಾ': 'maa',
    'ಮಿ': 'mi',
    'ಮೀ': 'mii',
    'ಮು': 'mu',
    'ಮೂ': 'muu',
    'ಮೃ': 'mr',
    'ಮೆ': 'me',
    'ಮೇ': 'mee',
    'ಮೈ': 'mai',
    'ಮೊ': 'mo',
    'ಮೋ': 'moo',
    'ಮೌ': 'mau',
    'ಮಂ': 'mam',
    'ಮಃ': 'mah',
    'ಯ': 'ya',
    'ಯಾ': 'yaa',
    'ಯಿ': 'yi',
    'ಯೀ': 'yii',
    'ಯು': 'yu',
    'ಯೂ': 'yuu',
    'ಯೃ': 'yr',
    'ಯೆ': 'ye',
    'ಯೇ': 'yee',
    'ಯೈ': 'yai',
    'ಯೊ': 'yo',
    'ಯೋ': 'yoo',
    'ಯೌ': 'yau',
    'ಯಂ': 'yam',
    'ಯಃ': 'yah',
    'ರ': 'ra',
    'ರಾ': 'raa',
    'ರಿ': 'ri',
    'ರೀ': 'rii',
    'ರು': 'ru',
    'ರೂ': 'ruu',
    'ರೃ': 'rr',
    'ರೆ': 're',
    'ರೇ': 'ree',
    'ರೈ': 'rai',
    'ರೊ': 'ro',
    'ರೋ': 'roo',
    'ರೌ': 'rau',
    'ರಂ': 'ram',
    'ರಃ': 'rah',
    'ಲ': 'la',
    'ಲಾ': 'laa',
    'ಲಿ': 'li',
    'ಲೀ': 'lii',
    'ಲು': 'lu',
    'ಲೂ': 'luu',
    'ಲೃ': 'lr',
    'ಲೆ': 'le',
    'ಲೇ': 'lee',
    'ಲೈ': 'lai',
    'ಲೊ': 'lo',
    'ಲೋ': 'loo',
    'ಲೌ': 'lau',
    'ಲಂ': 'lam',
    'ಲಃ': 'lah',
    'ವ': 'va',
    'ವಾ': 'vaa',
    'ವಿ': 'vi',
    'ವೀ': 'vii',
    'ವು': 'vu',
    'ವೂ': 'vuu',
    'ವೃ': 'vr',
    'ವೆ': 've',
    'ವೇ': 'vee',
    'ವೈ': 'vai',
    'ವೊ': 'vo',
    'ವೋ': 'voo',
    'ವೌ': 'vau',
    'ವಂ': 'vam',
    'ವಃ': 'vah',
    'ಶ': 'sha',
    'ಶಾ': 'shaa',
    'ಶಿ': 'shi',
    'ಶೀ': 'shii',
    'ಶು': 'shu',
    'ಶೂ': 'shuu',
    'ಶೃ': 'shr',
    'ಶೆ': 'she',
    'ಶೇ': 'shee',
    'ಶೈ': 'shai',
    'ಶೊ': 'sho',
    'ಶೋ': 'shoo',
    'ಶೌ': 'shau',
    'ಶಂ': 'sham',
    'ಶಃ': 'shah',
    'ಷ': 'ssha',
    'ಷಾ': 'sshaa',
    'ಷಿ': 'sshi',
    'ಷೀ': 'sshii',
    'ಷು': 'sshu',
    'ಷೂ': 'sshuu',
    'ಷೃ': 'sshr',
    'ಷೆ': 'sshe',
    'ಷೇ': 'sshee',
    'ಷೈ': 'sshay',
    'ಷೊ': 'ssho',
    'ಷೋ': 'sshou',
    'ಷೌ': 'sshaou',
    'ಷಂ': 'sshahm',
    'ಷಃ': 'sshah',
    'ಸ': 'sa',
    'ಸಾ': 'saa',
    'ಸಿ': 'si',
    'ಸೀ': 'sii',
    'ಸು': 'su',
    'ಸೂ': 'suu',
    'ಸೃ': 'sr',
    'ಸೆ': 'se',
    'ಸೇ': 'see',
    'ಸೈ': 'sai',
    'ಸೊ': 'so',
    'ಸೋ': 'soo',
    'ಸೌ': 'sau',
    'ಸಂ': 'sam',
    'ಸಃ': 'sah',
    'ಹ': 'ha',
    'ಹಾ': 'haa',
    'ಹಿ': 'hi',
    'ಹೀ': 'hii',
    'ಹು': 'hu',
    'ಹೂ': 'huu',
    'ಹೃ': 'hr',
    'ಹೆ': 'he',
    'ಹೇ': 'hee',
    'ಹೈ': 'hai',
    'ಹೊ': 'ho',
    'ಹೋ': 'hoo',
    'ಹೌ': 'hau',
    'ಹಂ': 'ham',
    'ಹಃ': 'hah',
    'ಳ': 'lla',
    'ಳಾ': 'llaa',
    'ಳಿ': 'lli',
    'ಳೀ': 'llii',
    'ಳು': 'llu',
    'ಳೂ': 'lluu',
    'ಳೃ': 'llr',
    'ಳೆ': 'lle',
    'ಳೇ': 'llee',
    'ಳೈ': 'llai',
    'ಳೊ': 'llo',
    'ಳೋ': 'lloo',
    'ಳೌ': 'llau',
    'ಳಂ': 'llam',
    'ಳಃ': 'llah',
  };
  Map<String, String> kannadaTransliteration = {
    '೦': '0',
    '೧': '1',
    '೨': '2',
    '೩': '3',
    '೪': '4',
    '೫': '5',
    '೬': '6',
    '೭': '7',
    '೮': '8',
    '೯': '9',
    '೴': 'om',
    '೵': '\u0964',
    '೶': '\u0965'
  };

  KannadaTransliterator() {
    kannadaCharList.addAll(kagunita);
    kannadaCharList.addAll(kannadaTransliteration);
  }

  // Function to transliterate a Kannada string to English
  String transliterateToEnglish(String kannadaText) {
    StringBuffer result = StringBuffer();
    int i = 0;

    while (i < kannadaText.length) {
      String currentChar = kannadaText[i];
      String nextChar = i + 1 < kannadaText.length ? kannadaText[i + 1] : '';

      if (kannadaCharList.containsKey(currentChar)) {
        String transliteration = kannadaCharList[currentChar]!;

        // Check for special cases like 'ಕ್ಷ', 'ರ್ಯ', etc.
        if (kannadaCharList.containsKey(currentChar + nextChar)) {
          transliteration = kannadaCharList[currentChar + nextChar]!;
          i++; // Increment to skip the next character as it's already processed
        } else if (nextChar == '್') {
          // Handle incorrect usage of '್'
          result.write(currentChar);
          i++; // Skip the '್' symbol
        }

        result.write(transliteration);
      } else {
        result.write(currentChar);
      }

      i++;
    }

    return result.toString();
  }

}

void testTransliteration(String kannadaText) {
  KannadaTransliterator kannadaTransliterator = KannadaTransliterator();
  String transliteratedText = kannadaTransliterator.transliterateToEnglish(kannadaText);
  print('Original Kannada Text: $kannadaText');
  print('Transliterated Text: $transliteratedText');
}

void main() {

  List<String> testSentences = [
    'ಅರ್ಪಿತಾ ಮಾಹಿತಿ',
    'ಈ ಕಥೆ ಸುಮಾರು ನಾಲ್ಕು ಸಾವಿರ ವರ್ಷಗಳ ಹಿಂದೆಯೂ ಇದ್ದುದು. ಇದು ಭಾರತದ ಮತ್ತು ವಿಶ್ವದ ಮಹಾಕಾವ್ಯವಾದ ಮಹಾಭಾರತದಿಂದ ಸೇರಿದ್ದು. ಇದು ಬೃಹದರಾಣ್ಯಕೋಪನಿಷತ್ತಿನಲ್ಲಿ ಮತ್ತು ಮಹಾಭಾರತದ ಅನೇಕ ಪ್ರಸಿದ್ಧ ವಿಚಾರಗಳಲ್ಲಿ ಉಕ್ತವಾಗಿದೆ. ಇದು ಆದಿ ಮತ್ತು ಅಂತ್ಯವಿಲ್ಲದಂತೆ ಕಾಣುವ ಒಂದು ವಸ್ತುವಿನ ಅನುಭವವನ್ನು ವಿವರಿಸಲು ಬರುತ್ತದೆ. ಇದು ಜ್ಞಾನ, ಭಕ್ತಿ, ಕರ್ಮ ಮತ್ತು ರಾಜಯೋಗದ ತತ್ತ್ವವನ್ನು ಪ್ರತಿಪಾದಿಸುತ್ತದೆ.',
    'ಶ್ರೀಕೃಷ್ಣನು ಅರ್ಜುನನಿಗೆ ಧರ್ಮಯುದ್ಧದ ಮಧ್ಯದಲ್ಲಿ ಮತ್ತು ಜೀವನದ ಸಮಸ್ಯೆಗಳ ಮಧ್ಯದಲ್ಲಿ ಪರಮಾತ್ಮನ ಸಂದೇಶವನ್ನು ಬೋಧಿಸುತ್ತಾನೆ. ಭಗವದ್ಗೀತೆಯು ಬಹುಮಾನಿತ ಗ್ರಂಥವಾಗಿದ್ದು ಅದು ಹಲವಾರು ಪ್ರಕಾರಗಳಲ್ಲಿ ಅನ್ವರ್ಥಿತವಾಗಿ ಪಠಿಸಲ್ಪಡುತ್ತದೆ. ಅದು ಧರ್ಮ, ಜ್ಞಾನ, ಭಕ್ತಿ, ಮೋಕ್ಷ, ಪ್ರೇಮ, ತ್ಯಾಗ, ಆತ್ಮವಿಕಾಸಗಳ ಮೇಲೆ ನಿಂತಿದೆ. ಅರ್ಜುನನ ಹೃದಯ ಬಾಗಿಲನ್ನು ತೆರೆದು ಅವನನ್ನು ಕರುಣೆಯಿಂದ ಆವೇಗಿಸುತ್ತಾನೆ.',
    'ಕನ್ನಡ ಸಾಹಿತ್ಯದಲ್ಲಿ ನಾಟಕಗಳ ಪರಂಪರೆ ಬಹಳ ಪುರಾತನವಾಗಿದ್ದು, ಮಹಾಕವಿ ಪಂಡಿತರಾಯರ ರಾಜಸಭೆಯ ಕಾಲದಲ್ಲಿ ಚಂದ್ರಾವತೀ ಎಂಬ ರಾಜನಾಟಕ ಮೊದಲಿನ ನಾಟಕವಾಗಿದ್ದು, ಈ ನಾಟಕವು ನಂದಿಕೇಶ್ವರ ವೃತ್ತಿಯಲ್ಲಿ ಬರಹವಾಯಿತೆಂದೂ, ಆದರೆ ಈ ನಾಟಕವು ಪ್ರಸ್ತುತ ದೊಡ್ಡಪ್ಪಟ ರೂಪವಾಗಿದೆಯೇ ಹೊರತು ಪುರಾತನ ನಾಟಕರೂಪದಲ್ಲಿ ಸಿಗುವಂತಿಲ್ಲದ್ದು, ಇಂದು ನಾಟಕವನ್ನು ಬರೆದಿರುವವರು ಹೆಚ್ಚು ಕಂಪನಿಗಳು ಹಾಗೂ ನಾಟಕಸಂಘಗಳೇ ಆಗಿದ್ದು, ಸಂಘ ಪ್ರಮುಖರು ಮಾತ್ರ ನಾಟಕ ಬರೆದುಕೊಂಡು ನಾಟಕವನ್ನು ನಾಟಕಸಂಘಗೆ ನೀಡುವವರೆಗೂ ಅವರ ಹೆಸರು ನಾಟಕಕ್ಕೆ ಬರುವುದಿಲ್ಲವೆಂದು ಗಮನಿಸಬೇಕಾಗಿದೆ.',
  ];

  // Run tests
  for (String sentence in testSentences) {
    testTransliteration(sentence);
    print('---------------------------');
  }
}

